services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "50051:50051"

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      - server
    environment:
      ROBOT_TARGET: server:50051
